FROM rust:1.70.0

WORKDIR /usr/src/myapp
COPY ./cc-assignment-2023 .

RUN apt-get update \
    && apt-get install -y cmake
RUN cargo install --path experiment-producer

ENTRYPOINT ["experiment-producer", "--brokers", "13.49.128.80:19093,13.49.128.80:29093,13.49.128.80:39093"]
